version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/openjdk:25.0.1'
    steps:
      - git-shallow-clone/checkout_advanced:
          clone_options: '--filter=blob:none'
      - run:
          name: "Git fetch"
          command: git fetch --no-filter --refetch
      - run:
          name: Analyze on SonarCloud
          command: mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -DskipTests

executors:
  jdk:
    docker:
      - image: 'cimg/openjdk:25.0.1'

orbs:
  maven: circleci/maven@2.1.1
  git-shallow-clone: guitarrapc/git-shallow-clone@2.8.0

workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: jdk
          context: OpenAI
      - build:
          context: SonarCloud